name: speakbetter_app
description: A language learning app for Korean/English practice
publish_to: "none"
version: 1.0.0+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  dio: ^5.7.0
  record: ^5.2.1
  permission_handler: ^11.3.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4
  uuid: ^4.5.1
  cupertino_icons: ^1.0.6
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  audioplayers: ^6.1.0
  pdf: ^3.11.1
  printing: ^5.13.3
  share_plus: ^10.1.2
  intl: ^0.19.0
  fl_chart: ^0.69.0
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  image_picker: ^1.1.2
  flutter_cache_manager: ^3.3.1
  connectivity_plus: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

dependency_overrides:
  record_linux: ^1.2.1
